# nixpacks.toml

# Menentukan bahwa ini adalah proyek PHP
providers = ["php"]

[phases.setup]
# Meminta Railway untuk menginstal PHP v8.3 dan ekstensi GD
nixPkgs = ["pkgs.php83", "pkgs.php83Extensions.gd"]

[start]
# Perintah untuk menjalankan aplikasi Anda
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"